services:
  postgres:
    container_name: task-master
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: task_master
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-taskmaster
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
networks:
  spring-taskmaster:
    driver: bridge

volumes:
  postgres:
    driver: local